config/routes.rb
ForumWithInheritedResources::Application.routes.draw do
  namespace 'forum' do
    resources :forum_threads
  end
end

app/models/forum_thread.rb
class ForumThread < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/forum/forum_threads_controller.rb
class Forum::ForumThreadsController < InheritedResources::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forum_threads_helper.rb
module ForumThreadsHelper
end

app/views/forum/forum_threads/_form.html.erb
<%= simple_form_for([:forum, @forum_thread]) do |f| %>

  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :subject %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/forum/forum_threads/edit.html.erb
<h1>Editing forum_thread</h1>

<%= render 'form' %>

<%= link_to 'Back', forum_forum_threads_path %>

app/views/forum/forum_threads/index.html.erb
<h1>Listing forum_threads</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @forum_threads.each do |forum_thread| %>
  <tr>
    <td><%= link_to 'Show', forum_thread %></td>
    <td><%= link_to 'Edit', edit_forum_thread_path(forum_thread) %></td>
    <td><%= link_to 'Destroy', forum_thread, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Forum thread', new_forum_forum_thread_path %>

app/views/forum/forum_threads/new.html.erb
<h1>New forum_thread</h1>

<%= render 'form' %>

<%= link_to 'Back', forum_forum_threads_path %>

app/views/forum/forum_threads/show.html.erb
<p id="notice"><%= notice %></p>

<%= @forum_thread.subject %>

<%= link_to 'Edit', edit_forum_forum_thread_path(@forum_thread) %> |
<%= link_to 'Back', forum_forum_threads_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ForumWithInheritedResources</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>